#!/bin/bash
# Script de información sobre el sensor de peso HX711

echo "================================================================"
echo "  SENSOR DE PESO HX711 - CONFIGURACIÓN"
echo "================================================================"
echo ""
echo "📊 ESTADO ACTUAL: DESACTIVADO (esperando conexión física)"
echo ""
echo "El servidor está preparado para recibir el sensor de peso HX711"
echo "cuando lo conectes. Por ahora retorna 0.0 kg para evitar"
echo "alertas falsas y el pitido molesto."
echo ""
echo "================================================================"
echo "  CÓMO CONECTAR EL SENSOR HX711"
echo "================================================================"
echo ""
echo "Conexiones GPIO:"
echo "  • HX711 VCC  → Raspberry Pi 5V (Pin 2 o 4)"
echo "  • HX711 GND  → Raspberry Pi GND (Pin 6, 9, 14, 20, 25, 30, 34, 39)"
echo "  • HX711 DT   → GPIO 5 (Pin 29)"
echo "  • HX711 SCK  → GPIO 6 (Pin 31)"
echo ""
echo "================================================================"
echo "  ACTIVAR SENSOR CUANDO LO CONECTES"
echo "================================================================"
echo ""
echo "1. Instalar librería HX711:"
echo "   cd ~/drone\\ acuatico"
echo "   source venv_pi/bin/activate"
echo "   pip install hx711"
echo ""
echo "2. Editar drone_server.py:"
echo "   - Buscar la función 'leer_sensor_peso()'"
echo "   - Descomentar las líneas del HX711 (están marcadas con #)"
echo "   - Comentar la línea: ultima_lectura_peso = 0.0"
echo ""
echo "3. Calibrar el sensor:"
echo "   - Ejecutar el script de calibración incluido en la librería"
echo "   - Ajustar los valores de calibración"
echo ""
echo "4. Reiniciar el servidor:"
echo "   pkill -f drone_server.py"
echo "   nohup python3 drone_server.py > drone_gps.log 2>&1 &"
echo ""
echo "================================================================"
echo "  CONFIGURACIÓN DE ALERTAS"
echo "================================================================"
echo ""
echo "• Umbral de alerta: 5.0 kg (configurable en PESO_UMBRAL)"
echo "• Frecuencia de lectura: cada 2 segundos"
echo "• Alerta visual: Panel parpadea en rojo"
echo "• Alerta sonora: Pitido cuando peso > umbral"
echo ""
echo "Para cambiar el umbral, edita en drone_server.py:"
echo "  PESO_UMBRAL = 5.0  # Cambiar a tu valor deseado"
echo ""
echo "================================================================"
echo "  VERIFICACIÓN ACTUAL"
echo "================================================================"
echo ""
echo "Estado del servidor:"
ps aux | grep drone_server | grep -v grep || echo "  ❌ Servidor no está corriendo"

if ps aux | grep drone_server | grep -v grep > /dev/null; then
    echo "  ✅ Servidor corriendo"
    echo ""
    echo "Última lectura de peso en logs:"
    grep "peso" ~/drone\ acuatico/drone_gps.log | tail -1 || echo "  Sin lecturas aún"
fi

echo ""
echo "================================================================"
echo ""
echo "RESUMEN:"
echo "  ✅ Pitido desactivado hasta conectar sensor"
echo "  ✅ GPS funcionando normalmente"
echo "  ✅ Sistema listo para sensor HX711"
echo ""
echo "================================================================"
