#!/bin/bash
# Generar código QR para acceso fácil desde celular

echo "================================================================"
echo "  ACCESO DESDE CELULAR - DRONE ACUÁTICO"
echo "================================================================"
echo ""
echo "✅ Servidor corriendo en:"
echo ""
echo "   IP:     192.168.1.8"
echo "   Puerto: 8080"
echo ""
echo "================================================================"
echo "  CÓMO ACCEDER DESDE TU CELULAR"
echo "================================================================"
echo ""
echo "1. Asegúrate de que tu celular esté en la misma red WiFi"
echo "   que la Raspberry Pi"
echo ""
echo "2. Abre el navegador de tu celular (Chrome, Safari, etc.)"
echo ""
echo "3. Escribe en la barra de dirección:"
echo ""
echo "   ┌─────────────────────────────────────┐"
echo "   │  http://192.168.1.8:8080           │"
echo "   └─────────────────────────────────────┘"
echo ""
echo "4. ¡Listo! Verás la interfaz de control con:"
echo "   • 📍 Mapa GPS en tiempo real"
echo "   • ⚡ Control de relés"
echo "   • 🎮 Control de movimiento"
echo "   • 📊 Sensor de peso (cuando lo conectes)"
echo ""
echo "================================================================"
echo "  CÓDIGO QR PARA ACCESO RÁPIDO"
echo "================================================================"
echo ""

# Generar código QR si qrencode está instalado
if command -v qrencode &> /dev/null; then
    qrencode -t ANSIUTF8 "http://192.168.1.8:8080"
    echo ""
    echo "Escanea este código QR con tu celular"
else
    echo "Para generar un código QR, instala qrencode:"
    echo "  sudo apt-get install qrencode"
    echo ""
    echo "Mientras tanto, puedes usar este servicio web:"
    echo "  https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=http://192.168.1.8:8080"
fi

echo ""
echo "================================================================"
echo "  VERIFICACIÓN"
echo "================================================================"
echo ""

# Verificar estado del servidor
if ps aux | grep -v grep | grep drone_server.py > /dev/null; then
    echo "✅ Servidor corriendo"
    echo "✅ Escuchando en 0.0.0.0:8080 (todas las interfaces)"
    echo "✅ Accesible desde cualquier dispositivo en la red"
else
    echo "❌ Servidor NO está corriendo"
    echo ""
    echo "Inicia el servidor con:"
    echo "  cd ~/drone\\ acuatico"
    echo "  source venv_pi/bin/activate"
    echo "  nohup python3 drone_server.py > drone_gps.log 2>&1 &"
fi

echo ""
echo "================================================================"
echo "  SOLUCIÓN DE PROBLEMAS"
echo "================================================================"
echo ""
echo "Si no puedes acceder desde el celular:"
echo ""
echo "1. Verifica que estés en la misma red WiFi:"
echo "   • Raspberry Pi: 192.168.1.8"
echo "   • Verifica tu celular en Ajustes > WiFi"
echo ""
echo "2. Prueba hacer ping desde tu celular:"
echo "   • Android: Usa app 'PingTools' o 'Network Utilities'"
echo "   • iPhone: Usa app 'Network Ping Lite'"
echo "   • Hacer ping a: 192.168.1.8"
echo ""
echo "3. Verifica firewall (poco probable en Raspberry Pi):"
echo "   sudo iptables -L | grep 8080"
echo ""
echo "4. Reinicia el servidor si es necesario:"
echo "   pkill -f drone_server.py"
echo "   cd ~/drone\\ acuatico && source venv_pi/bin/activate"
echo "   nohup python3 drone_server.py > drone_gps.log 2>&1 &"
echo ""
echo "================================================================"
echo "  TIPS"
echo "================================================================"
echo ""
echo "• Añade a favoritos en tu celular para acceso rápido"
echo "• Funciona en modo horizontal para mejor vista del mapa"
echo "• Los controles táctiles funcionan perfectamente"
echo "• Puedes tener múltiples dispositivos conectados"
echo ""
echo "================================================================"
